# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  rss_url: "https://cdn.flore.nz/example_feed.xml",
  # rss_url: "https://flore.nz/feed.xml",
  # rss_url: "https://www.tagesschau.de/infoservices/alle-meldungen-100~rss2.xml",
  display_mode_full: "grid_3", # grid, grid_2, grid_3, list, grid_list
  display_mode_half: "grid_list", # grid, list, grid_list
  display_mode_small: "list", # grid, list
  show_images_full: true,
  show_images_medium: true,
  show_images_small: true,
  show_description_full: true,
  show_description_medium: true,
  show_description_small: false,
  show_title_bar: true,
  title_pixel_perfect: true,
  description_pixel_perfect: true,
  }

# override variables
variables:
  trmnl: {}

