# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  rss_url: "https://cdn.flore.nz/example_feed.xml",
  display_mode_full: "grid",
  show_images_full: true,
  show_images_small: false,
  show_images_medium: false,
  show_description_full: false,
  show_description_small: false,
  show_description_medium: true}

# override variables
variables:
  trmnl: {}

